Tracker:AddLocations("locations/Floor 01.json")
Tracker:AddLocations("locations/Floor 02.json")
Tracker:AddLocations("locations/Floor 03.json")
Tracker:AddLocations("locations/Floor 04.json")
Tracker:AddLocations("locations/Floor 05.json")
Tracker:AddLocations("locations/Floor 06.json")
Tracker:AddLocations("locations/Floor 07.json")
Tracker:AddLocations("locations/Floor 08.json")
Tracker:AddLocations("locations/Floor 09.json")
Tracker:AddLocations("locations/Floor 10.json")
Tracker:AddLocations("locations/Floor 11.json")
Tracker:AddLocations("locations/Floor 12.json")
Tracker:AddLocations("locations/Floor 13.json")
Tracker:AddLocations("locations/Floor 14.json")
Tracker:AddLocations("locations/Floor 15.json")
Tracker:AddLocations("locations/Mirror Cleared !.json")
Tracker:AddLocations("locations/Overworld.json")
