Tracker:AddLocations("locations/Sinners/Yi Sang.json")
Tracker:AddLocations("locations/Sinners/Faust.json")
Tracker:AddLocations("locations/Sinners/Don Quixote.json")
Tracker:AddLocations("locations/Sinners/Ryoshu.json")
Tracker:AddLocations("locations/Sinners/Meursault.json")
Tracker:AddLocations("locations/Sinners/Hong Lu.json")
Tracker:AddLocations("locations/Sinners/Heathcliff.json")
Tracker:AddLocations("locations/Sinners/Ishmael.json")
Tracker:AddLocations("locations/Sinners/Rodion.json")
Tracker:AddLocations("locations/Sinners/Sinclair.json")
Tracker:AddLocations("locations/Sinners/Outis.json")
Tracker:AddLocations("locations/Sinners/Gregor.json")
Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/EGO/Yi Sang.json")
Tracker:AddLocations("locations/EGO/Faust.json")
Tracker:AddLocations("locations/EGO/Don Quixote.json")
Tracker:AddLocations("locations/EGO/Ryoshu.json")
Tracker:AddLocations("locations/EGO/Meursault.json")
Tracker:AddLocations("locations/EGO/Hong Lu.json")
Tracker:AddLocations("locations/EGO/Heathcliff.json")
Tracker:AddLocations("locations/EGO/Ishmael.json")
Tracker:AddLocations("locations/EGO/Rodion.json")
Tracker:AddLocations("locations/EGO/Sinclair.json")
Tracker:AddLocations("locations/EGO/Outis.json")
Tracker:AddLocations("locations/EGO/Gregor.json")