Tracker:AddLocations("locations/Yi Sang.json")
Tracker:AddLocations("locations/Faust.json")
Tracker:AddLocations("locations/Don Quixote.json")
Tracker:AddLocations("locations/Ryoshu.json")
Tracker:AddLocations("locations/Meursault.json")
Tracker:AddLocations("locations/Hong Lu.json")
Tracker:AddLocations("locations/Heathcliff.json")
Tracker:AddLocations("locations/Ishmael.json")
Tracker:AddLocations("locations/Rodion.json")
Tracker:AddLocations("locations/Sinclair.json")
Tracker:AddLocations("locations/Outis.json")
Tracker:AddLocations("locations/Gregor.json")
Tracker:AddLocations("locations/Overworld.json")
